feat(local-fhir): connect to a locally hosted fhir server
KitwareMedical/lungair-web-application pull request #22
Opened 2023-09-11 15:34 UTC by jadh4v

2023-09-12 18:53 UTC, ebrahimebrahim requested changes
This worked great! A few changes requested.

---

For me the first name is partly cut off:

![image](https://github.com/KitwareMedical/lungair-web-application/assets/1879759/59578190-e77a-458c-b223-dfeeadcfed15)

But if we are going to totally replace this UI element when we introduce a patient selector in #16 then we don't need to fix this here.

2023-09-12 18:53 UTC, ebrahimebrahim commented on lungair/src/components/LocalFHIR.vue
> +        <v-text-field class="mr-3"
Now that I look at it, I think this text field should go into `Settings.vue`. We could have a component `LocalFhirSettings.vue` paralleling `ServerSettings.vue` and `DicomWebSettings.vue`.

This will be a nice space to add more settings. For example later in #16 we will have a setting for the identifier system to be used for patient IDs.

2023-09-12 18:53 UTC, ebrahimebrahim commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
if I type in a bogus URL then the console shows the connection error nicely, but the user doesn't see anything. It would be good to show an error. We could have a generic status message property that can be populated with the various errors and other status messages we will need, and which would be hidden when empty. It could just be shown as text or it could be something like a [vuetify alert](https://vuetifyjs.com/en/components/alerts/).

2023-09-13 00:56 UTC, jadh4v commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
Added a vuetify alert like this:
<img width="419" alt="image" src="https://github.com/KitwareMedical/lungair-web-application/assets/22624785/b0b97a33-583d-4a9b-8e39-40984e018010">

2023-09-13 01:18 UTC, ebrahimebrahim commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
:heart_eyes:

2023-09-13 01:20 UTC, ebrahimebrahim commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
(but the alert should be below the connect button so that it's appearance doesn't displace the connect button)

2023-09-13 17:13 UTC, jadh4v commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
Moved to the bottom:
<img width="338" alt="image" src="https://github.com/KitwareMedical/lungair-web-application/assets/22624785/4817d342-e46c-4aef-a3ff-b6e9d564e2a4">

2023-09-13 17:14 UTC, jadh4v commented on lungair/src/components/LocalFHIR.vue
> +  const res = await client.request("Patient");
Also the link won't be visible now since we are removing the textbox. It will be visible/editable from the settings window, with other servers' settings.

2023-09-13 20:47 UTC, jadh4v commented on lungair/src/components/LocalFHIR.vue
> +        <v-text-field class="mr-3"
I have added a preliminary `store/local-fhir-store` for persistent information regarding the local FHIR server.
Also added `LocalFhirSettings.vue` which is a component of the settings dialog. So basically moved the URL text box to the settings dialog.

2023-09-13 20:48 UTC, jadh4v commented
Some cosmetic issues will get resolved when we decide on the patient list user-interface.

2023-09-15 19:27 UTC, ebrahimebrahim approved these changes
Tested again and it worked very nicely.

Changes all look good.

I noticed I get an error in console
```
read-dicom-tags.umd.js:9 Could not read the input DICOM file
```
when the page loads, but then I found that this error happens on lungair-main as well. Maybe something is weird with my local orthanc setup.

2023-09-15 20:28 UTC, jadh4v commented
> Tested again and it worked very nicely.
> 
> Changes all look good.
> 
> I noticed I get an error in console
> 
> ```
> read-dicom-tags.umd.js:9 Could not read the input DICOM file
> ```
> 
> when the page loads, but then I found that this error happens on lungair-main as well. Maybe something is weird with my local orthanc setup.

could be coming from core Volview. I have seen similar error there as well.

2023-09-15 20:29 UTC, merged