feat(seg-server): Add a new segmentation server
KitwareMedical/lungair-web-application pull request #41
Opened 2024-02-01 02:03 UTC by jadh4v

Add a new DL model based segmentation server
based on customization of Volview's Python server.

2024-02-01 02:10 UTC, jadh4v commented on lungair/server/pyproject.toml
> +priority = "explicit"
ML related dependencies

2024-02-07 17:01 UTC, jadh4v commented
Additional fixes for visualizing the overlay will be done in a separate PR.

2024-02-13 03:35 UTC, ebrahimebrahim requested changes
Really nice work on this. A couple of minor changes requested and then we can go ahead and merge this.

I tested this and got it to work and show the segmentation mask! As a binary mask image and not an annotation, as expected.

But I had to fiddle with the code to get it to use cpu only. This is because the cuda version on my system isn't compatible with the torch version that this requires. I can normally use older versions of pytorch just fine, and I still get `torch.cuda.is_available()` being true even with the environment setup here with torch 2.1.2+cu121. So the lung segmentation code thinks I am fine to use cuda and tries to use it and fails, hence the need to fiddle with it and force it to use CPU.

Because of this I suggest one more change:
- _either_ make cpu the default behavior so that one has to deliberately go and enable gpu in some config setting somewhere, making this work more reliably out of the box,
- _or_ add to the python server readme the system requirements (cuda version whatever) so that it's more clear to the user when this is expected to fail on their system

2024-02-13 03:35 UTC, ebrahimebrahim commented on lungair/server/README.md
> +poetry install
After this step the dependencies were installed just fine but at the end I got this:

```txt
Installing the current project: volview_server (0.1.0)
The current project could not be installed: No file/folder found for package volview-server
If you do not want to install the current project use --no-root
```

This is despite the fact that the earlier poetry install step already installed `volview-server`. Running this command actually broke the previously installed `volview-server`, so that subsequent attempts to run `volview_server` would fail.

I think one solution is to add `--no-root` to this install command as the error message suggests.

2024-02-13 03:35 UTC, ebrahimebrahim commented on lungair/server/lungair_seg_inference.py
> +    transform_dict = pre_transforms(input_dict)
After switching over to cpu-only (see my final review message for context), I got an error at this `pre_transforms` step:

```txt
Traceback (most recent call last):
  File "/home/ebrahim/lungair-web-application-test/.venv/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/ebrahim/lungair-web-application-test/.venv/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/ebrahim/lungair-web-application-test/.venv/lib/python3.9/site-packages/monai/transforms/utility/dictionary.py", line 266, in __call__
    d[key] = self.adjuster(d[key], meta_dict)
  File "/home/ebrahim/lungair-web-application-test/.venv/lib/python3.9/site-packages/monai/transforms/utility/array.py", line 204, in __call__
    img = MetaTensor(img)
  File "/home/ebrahim/lungair-web-application-test/.venv/lib/python3.9/site-packages/monai/data/meta_tensor.py", line 116, in __new__
    return torch.as_tensor(x, *args, **_kwargs).as_subclass(cls)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

Replacing `input_img`  by `input_img.astype(int)` fixed this problem. I guess the itk array converter gave the image in a weird type `numpy.uint16`.

But you said that you tried cpu-only and it worked, so I wonder why only I had to do this.

2024-02-16 01:39 UTC, jadh4v commented on lungair/server/README.md
> +poetry install
There's a `package-mode = false` property but it is yet to be released (poetry v1.8.0, see: https://python-poetry.org/docs/master/basic-usage/#operating-modes)
I suppose `--no-root` is our best option right now.

2024-02-16 01:47 UTC, jadh4v commented on lungair/server/lungair_seg_inference.py
> +    transform_dict = pre_transforms(input_dict)
Added a default conversion to int as suggested.

2024-02-16 01:51 UTC, jadh4v commented
> This is because the cuda version on my system isn't compatible with the torch version that this requires. I can normally use older versions of pytorch just fine, and I still get torch.cuda.is_available() being true even with the environment setup here with torch 2.1.2+cu121.


I'm a bit confused about the cuda requirements issue. Isn't the virtual env created by poetry supposed to install the correct version of torch+cuda?
Are you running the server with `poetry run` command?

2024-02-16 04:16 UTC, ebrahimebrahim commented
> I'm a bit confused about the cuda requirements issue. Isn't the virtual env created by poetry supposed to install the correct version of torch+cuda? Are you running the server with `poetry run` command?

It does install the correct version of torch that is meant to go with the correct version of cuda, but I think the actual version of cuda that is installed on the system is a system-level thing. The virtual env can't touch that. Upgrading cuda is similar to upgrading the video drivers on my system. if I understand correctly

2024-02-16 04:22 UTC, ebrahimebrahim approved these changes
Looks good, ty!

For my last remaining comment you can just add a comment to the python server readme saying what version of CUDA is required to be on the system. then this is good to merge

2024-02-16 16:28 UTC, jadh4v commented
Ok understood. I guess we could also later try to _catch_ the cuda exception and switch to CPU inference during runtime.

2024-02-16 16:35 UTC, merged